### ISSUE TITLE
User data privacy clarification

### ISSUE THREAD

**Issue by ningsongshen** [virtrolio/virtrolio-site#53]
**Describe the bug**
I would like to know who has the ability to read the messages that I write/receive. Are they encrypted? Do the devs have access to them? What about big brother Google?  Preferably this is emphasized somewhere prominent, because you guys seem to put a lot of emphasis on referring to the privacy policy and TOS but don't talk about this other issue. And, messages are often very personal, so it's best to keep them safe. Yearbooks are offline, but virtrolio is not so there are some additional risks.

Also, it would be helpful to have an explainer for the privacy policy, for people who are not legal experts or don't have time (like me). I read the privacy policy and was not able to determine if the notes I send are encrypted/private, or if you guys have access to them, etc. I could only find info on name, email, profile picture which tbh are probably already out in the wild.

**Comment by GuyInFridge** [comment]
We were considering adding 'TL;DR Summaries' to our TOS and Privacy Policy. @anthonyftwang can start working on those since the TOS and Privacy Policy are kinda hard to read.

As for your data, your Name/Email/Profile picture are all coming from Google. Messages are not encrypted and are stored as raw Markdown text, and are not kept private from the Firebase administrators, but they are kept private from other virtrolio users who are not Firebase administrators. I am not entirely sure on how much of our database content Google can view directly— @ricetech can probably answer that better.

Does that help?

**Comment by ningsongshen** [comment]
Sure.

🙌

**Comment by ricetech** [comment]
This issue was resolved in pull request #73.
