### ISSUE TITLE
Improving Beta tester setup

### ISSUE THREAD

**Issue by ningsongshen** [virtrolio/virtrolio-site#56]
**Is your feature request related to a problem? Please describe.**
The beta tester instructions are a bit unorganized and there's too much to read in many different places. imo not the right things are being emphasized.

**Describe the solution you'd like**
An outline of the main steps to take, and then details for those that need it. For example, I already had Git, Node, VSCode installed so the installation was faster than I thought it was going to be. But I still read through it anyway 😄 . It would be faster if i just knew that I had to install @angular/cli and `npm i` to get things going. 

Maybe I joined late but lots of somewhat not-important-anymore stuff in beta-announcements.

And I'm not sure exactly what intentions are with beta testers, but maybe removing setup would be best to test user behaviour (like having a beta site).

If the beta testers are becoming contributors, perhaps include more docs to setup for dev? idk

@ricetech you're doing great buddy, 🎯  

**Additional context**
Beta testers.

**Comment by GuyInFridge** [comment]
@ricetech would it be possible to make a beta virtrolio website using another Firebase project? Can we have the beta website hosted on another URL but with the data still in sync with the data from the main database? One concern about this is what if some other people found out about the beta website? Is there any way to go about minimizing the risk/consequences of that happening? In terms of front end, we could change the title text to blatantly read [BETA TESTERS ONLY] or something.

Also Ningsong, I agree that `#beta-announcements` is cluttered with currently irrelevant stuff. My impression was that it would be updated every few days with new stuff so it would fill up, but I can see that that would be confusing. @ricetech and I will work on cleaning that up. As for the instructions, if we get rid of the Beta Tester Docs and move to a beta website, then `#instructions` on the Discord would be the only place that Beta testers should have to go for their instructions (right @ricetech?), so that would make it easier for them. The instructions would also be reworded to help in this regard.

**Comment by ricetech** [comment]
Yes, I believe it's possible to have multiple websites on one project. I will look into it, but it might be a paid feature.
And yes, we can definitely make the instructions less complicated. The specific method will depend on how the first part plays out, though.

**Comment by ricetech** [comment]
This issue has been resolved by the creation of a separately hosted beta website as well as Pull Request #74.

**Comment by ningsongshen** [comment]
Wow these devs are fantastic. Keep it up. 😎
