### ISSUE TITLE
Encrypted/private messages

### ISSUE THREAD

**Issue by ningsongshen** [virtrolio/virtrolio-site#57]
**Is your feature request related to a problem? Please describe.**
In a previous issue, it was mentioned about user data that the messages people send on the platform are not private and can be viewed by the admins or virtrolio.

**Describe the solution you'd like**
Messages are only readable by sender/receiver.

Yearbooks are personal things, so it should be the same online. Not saying that you guys will do malicious things with the data, but there is always another access point, another risk... People will be more comfortable knowing the messages are private.

**Additional context**

**Comment by GuyInFridge** [comment]
@ricetech do you have any way of doing this through Firebase?

**Comment by ricetech** [comment]
From what I can tell, encryption would be rather difficult using the current system, but I'll certainly look into it. In the meantime, I'm confident that our current system of a robust set of security rules combined with limiting the number of Firebase administrators to an absolute minimum will be robust enough to prevent unwanted access, but I should also point out that many services that people entrust with their personal data daily such as Facebook Messenger are not encrypted by default.

**Comment by ArvindN0** [comment]
While we have considered encrypting all messages, here's why we haven't:
1) Information that requires that kind of encryption would be SIN numbers, bank account information, and other highly confidential data which simply isn't the purpose of our service so we don't foresee implementing message encryption. 
2) The majority of messaging services to not do the kind of encryption you are suggesting and so it's not something we'd be doing either. 
3) In order to enforce our terms of service, we need to have access to the messages to ensure that negative content that violates our TOS isn't being shared through our site. 
That being said, I can pinkie promise we won't do anything malicious with your content :))
P.S. It's also kinda hard to do lol

**Comment by ningsongshen** [comment]
Ok, thanks for considering the suggestion. Looks like the team does an excellent job of prioritization.

Kudos on the app.
