### ISSUE TITLE
Clicking the bold/italic button multiple times

### ISSUE THREAD

**Issue by ningsongshen** [virtrolio/virtrolio-site#67]
**Describe the bug**
When clicking the bold/italic button multiple times, a bunch of asterisks are just added to the text. I know that you guys are using MD but those that don't know might expect a different outcome.

**To Reproduce**
Highlight text and click bold/italic button.

**Expected behavior**
Clicking the bold/italic should add asterisks, clicking again should remove them.

**Comment by DabeerAzeez** [comment]
We were thinking of adding a feature so that if they double tap a formatting button then the selected text will be formatted and then unformatted. The harder issue to tackle is if someone formats some text, moves their cursor, and then goes back into the text that they want to unformat. Accommodating for edge cases could be difficult, especially if we have text like `**Hello*what***`. I have assigned @TommyHuang-dev to this issue if you have further questions.

**Comment by anthonyftwang** [comment]
Yes implementing something robust is non-trivial and even popular editors like Typora see some unexpected behavior re: edge cases. An interesting theoretical exercise perhaps but for the sake of efficiency, maybe use this instead:

https://ej2.syncfusion.com/angular/documentation/rich-text-editor/getting-started/

**Comment by LillianHuang-dev** [comment]
Issue closed for now, this feature would take a long time to implement and unfortunately I don't see it being added anytime soon.
