### ISSUE TITLE
Cannot edit my message.

### ISSUE THREAD

**Issue by ningsongshen** [virtrolio/virtrolio-site#68]
**Describe the bug**
The warning is too scary. In real life you can somewhat 'edit' your message until it looks perfect on the book. Here, there's a scary submit button.

**Comment by DabeerAzeez** [comment]
We added more 'friendly' wording to the 'Submit' button (it says 'Send' instead) to help reduce how scary it is. We wanted to implement this warning because it is a lot harder to 'take something back' once it's been sent to our database versus if you wanted to redo the message that you wrote in someone else's yearbook. You can of course edit your message as much as you want _before_ you submit.

If you don't have some more specific suggestions for how to change this feature, we don't see how we might do this differently.
